Band = ["puma",
        "radical",
        "pesudo",
        "nightmare",
        "szittya",
        "elegant",
        "simple",
        "homeless",
        "boys",
        "mates",
        "lányok",
        "digital",
        "édes",
        "fiúk",
        "hot",
        "háttérsugárzás",
        "villanás",
        "ásítás",
        "magányos",
        "zseni",
        "compact",
        "rózsa",
        "lila",
        "galaxisok",
        "deep",
        "szandál",
        "live",
        "analog",
        "döglött",
        "sáska",
        "ellenreakció",
        "legál",
        "nyers",
        "barbie",
        "gumi",
        "állatok"
       ]

Artist = ["Johnny",
         "Lakatos",
         "Szabó",
         "Cápa",
         "Főnök",
         "Sás",
         "Lajos",
         "Bitumen",
         "Fajzat",
         "Dúvad",
         "Dámvad",
         "Édeske",
         "Gyöngyianett",
         "Farkas",
         "Rothfeld",
         "Sandeep",
         "Kumar",
         "Tonhal",
         "Latyak",
         "Pelikán",
         "Doki",
         "MC",
         "Maryann",
         "McWirsli",
         "Karaj",
         "Csámpás",
         "Kancsi",
         "Rozi",
         "Thybault",
         "Mózes",
         "'TheGun'",
         "Steigerwald",
         "Dylan",
         "Sawyer",
         "Maverick",
         "'The Ugly'",
         "Messiah",
         "Tobias",
         "Patkány",
         "Rotten",
         "Palack",
         "Tubus",
         "Ampulla",
         "Kisser",
         "Trixter",
         "Hopper",
         "Agape",
         "Flipper",
         "Azula",
         "Crystal",
         "Destiny",
         "Felicity",
         "Hotshot",
         "Trio",
         "Buksi",
         "Pista",
         "Kesztyűs",
         "Hermész",
         "Répa",
         "Achilles",
         "Salak",
        ]
        
Member = ["frontembere",
          "basszusgitárosa",
          "menedzsere",
          "vokalistája",
          "neppere",
          "szaxofonosa",
          "szintise"
         ]

Band2 = ["és a",
         "meg a",
         "és a"
        ]

Date = ["2015-ben", 
        "2011-ben",
        "2016-ban",
        "2006-ban",
        "2012-ben",
        "2019-ben",
        "nemrégiben",
        "a rendszerváltás után",
        "a berlini fal leomlásakor",
        "érettségi után",
        "két sör után",
        "három sör és kettő Jäger után",
        "a konzervatóriumból való kicsapása után",
        "a gyárból (the factory) való elbocsátása után",
        "egyik kocsmából való távozása után",
        "a közelmúltban",
        "nem tudni pontosan mikor",
        "tavaly",
       ]

Inspiration = ["döglött legyek", 
               "lélekvándorlás",
               "DIY dekorációk",
               "lepattant gördeszkás helyek",
               "hosszas sorbanállás",
               "eladási listák",
               "gyógyhatású kövek",
               "hóvégi leégés",
               "tizenegy utáni sztoftpornó",
               "tigáz számlák",
               "Francia Forradalom",
               "kurrens tudatmódosítók",
               "Kádári gazdaságpolitika",
               "multinacionális vállalatok",
               "sztoikus válóperes ügyvédek",
               "joviális félőrültek",
               "őszinte meth függők",
               "fröccsöntött műanyag koktélnapernyők",
               "sajtószabadság",
               "Észak afrikában őshonos kajmánok",
               "apácák",
               "megbokrosodott pónik",
               "népszerű nyugdíjasok",
               "agyontuningolt autóroncsok",
               "túlméretezett csuklós buszok",
               "építőmunkások",
               "BKV-s közlekedés",
               "a Blaha Lujza téri aluljáró",
               "kiégett meztelen delfinek",
               "halott búgócsigák",
               "veszett mókusok",
               "négyes metró",
               "udvarias BKV ellenőrök",
               "befalazott fotóművészek",
               "túlhaladott világnézetek",
               "spirális kenőpénzek",
               "részegen elsuttogott féligazságok",
               "történelmi egyházak",
               "kifulladt valóságsók",
               "elrontott érettségi vizsgák",
               "elszalasztott lehetőségek",
              ]

Adverb = ["mindeközben",
          "gyakran",
          "számtalanszor",
          "szép lassan",
          "apránként",
          "alattomos tempóban",
          "lassan de biztosan",
          "nem spórólva",
         ]

Song_Title = ["And",
              "The",
              "Obey",
              "Hack",
              "Cry",
              "Modern",
              "Full",
              "Try",
              "Chips",
              "End",
              "Chemichal",
              "My",
              "Hot",
              "Cool",
              "Trip"
             ]

Style1 = ["proto",
          "poszt",
          "nyugger",
          "multiinstrumentalista",
          "neo",
          "oldschool",
          "newschool",
          "rafinált",
          "prosztó",
          "suttyó",
          "alvilági",
          "keresztény",
          "jiddis",
          "ezoterikus",
          "taoista behatású",
          "deszkás",
          "alter",
          "DIY",
          "fizetős,",
          "határidős",
          "radical",
          "hacker",
          "avantgard",
          "dark",
          "mulatós",
          "art",
          "zen",
          "nudista",
          "transzcendentális",
          "shoegaze",
          "kortárs",
          "indie",
          "sittes",
          "szittya",
          "szinti",
          "nutri",
          "regölős",
          "space",
          "homeless",
          "hardcore",
          "fúziós",
          "letisztult",
          "soft",
          "poszt",
          "hátradőlős",
          "független",
          "kórus",
          "alakítgatós",
          "úszós",
          "mesélős",
          "kommersz",
          "vokális",
          "undergrund",
          "posztmodern",
          "újhullámos",
          "experimental",
          "indusztriális",
          "eklektikus",
          "alternatív"
         ]

Style2 = ["funky",
          "funky",
          "break",
          "hip-hop",
          "trash",
          "techno",
          "drum and bass",
          "dream pop",
          "mumbai jazz",
          "hárfa",
          "bossanova",
          "indie",
          "jazz",
          "blues",
          "trance",
          "kamarazene",
          "disco",
          #"rock and roll",
          "rap",
          "bullshit",
          "grunge",
          "operett",
          "country",
          "pop",
          "goa",
          "garázspop",          
          "soul",
          "pszichedélia",
          "punk",
          "lo-fi",
          "house",
          "trap",
          "stoner",
          "garázsrock",
          #"elektro",
          #"rock"
         ]

Adjective = ["sokszínű",
             "monotonnak korántsem mondható",
             "őrületes",
             "még mindig nagyon friss",
             "újszerű",
             "eklektikus",
             "túlhúzott",
             "brutális",
             "paradigmaváltó",
             "karanténromboló",
             "titokzatos",
             "kissé excentrikus",
             "összetett",
             "odamondós",
             "rímközpontú",
             "elszállós",
             "kozmikus",
             "kommersz",
             "performatív",
             "éteri",
             "eszeveszett",
             "meleg",
             "pörgős",
             "döglesztő",
             "súlytó",
             "veretős",
             "átfogó",
             "hippi",
             "riffközpontú",
             "archaikus",
             "világzenei",
             "erősen modulált",
             "megfoghatatlan",
             "körülírhatatlan",
             "kísérletező",
             "esztetizáló",
             "barokkos",
             "szintetizáló",
             "újhullámos",
             "extatikus",
             "letisztult",
             "sokrétű",
             "izmos",
             "klasszikus",
             "őrjöngő",
             "steampunk-szerű",
             "cyberpunk jellegű",
             "szittya",
             "imporovizatív",
             "lüktető",
             "rafinált",
             "egyedi",
             "sötét hangulatú",
             "lendületes",
             "sodró",
             "kultikus",
             "izgalmas",
             "komplex",
             "friss",
             "katarktikus",
             "random",
            ]

Location = ["hazai", 
            "külföldi", 
            "vidéki",
            "virális",
            "menő",
            "karácsonyi",
            "friss",
            "spotify",
            "trendi",
            "papagájoknak szóló",
            "mély ihletettségű",
            "gyerekeknek szóló",
            "nyugdíjasoknak szóló",
            "suttyúknak szóló",
            "neo-vandáloknak szóló",
            "rendszerváltásról szóló",
            "szubliminálisan irritáló",
            "tudatalatti",
            "új-fundlandi",
            "csehszlovák",
            "rákospataki",
            "taksonyi",
            "boszniai",
            "óbudai"
            ]

Country = ["Szerbiában", 
           "Azerbajdzsánban",
           "Finnországban",
           "Örméynországban", 
           "Albániában",
           "Egyiptomban",
           "Cipruson",
           "Jugoszláviában",
           "Vatikánban",
           "Kirgigisztánban",
           "Csehszolvákiában",
           "Fehéroroszrországnban",
           "Ukrajnában",
           "Erdélyben",     
           "a Művészetek völgyében",
           "a Colorádó fesztiválon",
           "Hana Hana fesztiválon",
           "Októberfesten",
           "a Szovjetúnióban",
           "a Kajmán Szigeteken",
           ]
